### ISSUE TITLE
Not related to anything (chat)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Wyn-Price/Wyn-Price.github.io#1]
hey I noticed your a quick coder can you port a mod for my wife its called magic clover.
https://github.com/konwboj/MagicClover

to 1.12.2? @Wyn-Price

**Comment by Wyn-Price** [comment]
I mean I can try. Im not bust at the moment so I can do that

**Comment by P3rf3ctXZer0** [comment]
You would make he insanely happy ;) thanks :)

**Comment by Wyn-Price** [comment]
ok i think i got it all sorted. Just looking checking

**Comment by P3rf3ctXZer0** [comment]
Thanks I know she will be so happy <3

**Comment by Wyn-Price** [comment]
Ok clinet side works, testing server

**Comment by P3rf3ctXZer0** [comment]
okay waiting for mod to start up server. That way my players won't have to deal with me shutting down server anymore today ;) unless something breaks.

**Comment by Wyn-Price** [comment]
on done. Ill send it to you now

**Comment by Wyn-Price** [comment]
[here you go :)](https://drive.google.com/file/d/0B38KQkz251dQSktkeUhfeWVRQ2c/view?usp=sharing)
